### ISSUE TITLE
引擎头呢

### ISSUE THREAD

**Issue by Djcn** [AppCanOpenSource/appcan-plugin-demo-ios#1]
如题

**Comment by AppCanOpenSource** [comment]
直接引入AppCanKit.framework

**Comment by connyliu** [comment]
4.0插件不再需要引入引擎头文件
对于oc插件,只需要引入AppCanKit这个framework即可,包含插件开发相关的所有内容
对于swift插件,需要同时引入AppCanKit以及AppCanKitSwift这2个framework
